introduce markdown-lint

diff --git a/bin/check b/bin/check
--- a/bin/check
+++ b/bin/check
@@ -13,6 +13,12 @@ if [ ! $RC -eq 0 ]; then
   exit 1
 fi
 
+mdl .
+if [ ! $? -eq 0 ]; then
+  echo 'Violated markdown rules, see https://github.com/mivok/markdownlint/blob/master/docs/RULES.md, commit aborted'
+  exit 1
+fi
+
 bundle exec rspec
 if [ ! $RC -eq 0 ]; then
   echo 'rspec errors'
